baseURL = 'https://bebechien.github.io/cozy-corner-future/'
languageCode = 'en-us'
title = 'Cozy Corner Future'
theme = 'terminal'
pagination.pagerSize = 5

# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
  noClasses = false

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = true

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = false

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default

  # Set date/time format for posts
  # This will impact the date/time displayed on
  # index.html, the posts list page, and on posts themselves
  # This value can also be configured per-post on front matter
  # If you have any issues with the timezone rendering differently
  # than you expected, please ensure your timezone is correctly set
  # on your server.
  # This value can be customized according to Hugo documentation:
  # https://gohugo.io/functions/time/format/
  # Default value (no changes needed):
  # dateFormat = "2006-01-02"
  # Example format, with date, time, and timezone abbreviation:
  # dateFormat = "2006-01-02 3:04:06 PM MST"

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = 'English'
    contentDir = 'content/en'
    weight = 10
    title = 'Cozy Corner Future'

    [languages.en.params]
      readMore = "Read more"

    [languages.en.params.logo]
      logoText = "Cozy Corner Future"
      logoHomeLink = "/cozy-corner-future/en/"
    
    [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about"

        [[languages.en.menu.main]]
          identifier = "posts"
          name = "Posts"
          url = "/posts"

  [languages.ko]
    languageName = '한국어'
    contentDir = 'content/ko'
    weight = 20
    title = '방구석 퓨처'

    [languages.ko.params]
      readMore = "Read more"

    [languages.ko.params.logo]
      logoText = "방구석 퓨처"
      logoHomeLink = "/cozy-corner-future/ko/"
    
    [languages.ko.menu]
        [[languages.ko.menu.main]]
          identifier = "about"
          name = "About"
          url = "/ko/about"

        [[languages.ko.menu.main]]
          identifier = "posts"
          name = "Posts"
          url = "/ko/posts"

  [languages.ja]
    languageName = '日本語'
    contentDir = 'content/ja'
    weight = 30
    title = 'すみっコの未来'

    [languages.ja.params]
      readMore = "Read more"

    [languages.ja.params.logo]
      logoText = "すみっコの未来"
      logoHomeLink = "/cozy-corner-future/ja/"
    
    [languages.ja.menu]
        [[languages.ja.menu.main]]
          identifier = "about"
          name = "About"
          url = "/ja/about"

        [[languages.ja.menu.main]]
          identifier = "posts"
          name = "Posts"
          url = "/ja/posts"

