name: DEV.to Publisher

on:
  push:
    branches:
      - 'devto-sync'

jobs:
  deploy-to-devto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Publish to DEV.to
        uses: sinedied/publish-devto@v2
        with:
          files: 'articles/**/*.md'
          devto_key: ${{ secrets.DEVTO_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          conventional_commits: true
          branch: 'devto-sync'
          dry_run: false
