name: Publish to DEV.to
on:
  push:
    paths:
      - 'content/en/**' # Trigger only on English content
      - 'scripts/prepare_devto.py'
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-to-devto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install python-frontmatter toml

      - name: Prepare Distribution
        run: |
          mkdir -p devto_dist/posts/images
          cp static/images/* devto_dist/posts/images

      - name: Prepare Content (Fix Images & Metadata)
        run: python scripts/prepare_devto.py

      - name: Deploy to DEV.to Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./devto_dist
          publish_branch: devto-sync
          commit_message: "chore: sync content from main [skip ci]"

      - uses: actions/checkout@v6
        with:
          ref: devto-sync

      - name: Publish to DEV.to
        uses: sinedied/publish-devto@v2
        with:
          devto_key: ${{ secrets.DEVTO_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: 'posts/**/*.md'
          conventional_commits: true
          branch: devto-sync
